### ISSUE TITLE
[FE] Creation of error messages

### ISSUE THREAD

**Issue by AnnaH3003** [amosproj/amos2023ws01-ticket-chat-ai#122]
## User story
1. As a user
2. I want / need to know when a ticket could not be created
3. So that I can try again

## Task
Create two error messages for the following cases:
1. User did not input any data 
2. The input could not be delivered to the TalkTixChatAPI

## Acceptance criteria

- [ ] an error message is displayed when user did sumbit without providing any input
- [ ] an error message is displayed if the input could not be sent to the TalkTixChatAPI
- [ ] the error messages state the formulations above

## Definition of done (DoD)
- Work products are uploaded to the Github repository and merged to the main branch
- If necessary, the bill of materials section of the planning documents is updated
- Code/feature passes suited tests
- Code is peer-reviewed
- Help documentation (README) is updated
- Fits into our architecture, where possible

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release
