### ISSUE TITLE
Locations

### ISSUE THREAD

**Issue by thogebati** [amosproj/amos2023ws01-ticket-chat-ai#131]
##Task
We need to be able to allocate services or locations to our tickets.

For this we need to create:

- [ ] User database should map users to a specific location
- [ ] location database, 10 locations
- [ ] service database, to check if the KI assigned a valid service. 

The user profile is used to allocate a location to a ticket, if no service is affected. If no location is found, use feedback loop to ask for location.
Service is allocated by specific keywords.

## Acceptance criteria
* Criterion 1
* Criterion 2
* ...

## Definition of done (DoD)
- Work products are uploaded to the Github repository and merged to the main branch
- If necessary, the bill of materials section of the planning documents is updated
- Code/feature passes suited tests
- Code is peer-reviewed
- Help documentation (README) is updated
- Fits into our architecture, where possible

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release
