### ISSUE TITLE
Create User Database -TODO

### ISSUE THREAD

**Issue by thogebati** [amosproj/amos2023ws01-ticket-chat-ai#135]
## User story
1. As a user
2. I want / need user database
3. So that my Name and location is stored and I don't have to enter it every time.

## Acceptance criteria

- [ ] a new table in the database is created.
- [ ] with the following columns: ID, name, surname, email, location and password.
- [ ] the following users should be predefined:  

## Definition of done (DoD)
- Work products are uploaded to the Github repository and merged to the main branch
- If necessary, the bill of materials section of the planning documents is updated
- Code/feature passes suited tests
- Code is peer-reviewed
- Help documentation (README) is updated
- Fits into our architecture, where possible

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release
