### ISSUE TITLE
Research on further possible suitable data sets

### ISSUE THREAD

**Issue by AnnaH3003** [amosproj/amos2023ws01-ticket-chat-ai#143]
## Task
Since a lot of data is required for the AI training, it might prove helpful to search for similar data sets publicly available that we could consequently adjust to suit our purposes.

Check open data portals such as e.g. Mobilithek, European Data Portal, GovData, GitHub, awesomedata/awesome-public-datasets: A topic centric list of HQ open datasets amongst others.

## User story
1. As a developer training an AI
2. I want / need a large data set consistent with my use case
3. So that I can train the AI properly

## Acceptance criteria
- [ ] research is concuted
- [ ] potential data sets are noted 
- [ ] effort required to align the data set with our template is evaluated

## Definition of done (DoD)
- Work products are uploaded to the Github repository and merged to the main branch
- If necessary, the bill of materials section of the planning documents is updated
- Code/feature passes suited tests
- Code is peer-reviewed
- Help documentation (README) is updated
- Fits into our architecture, where possible

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release
