### ISSUE TITLE
User Profile - Epic

### ISSUE THREAD

**Issue by AnnaH3003** [amosproj/amos2023ws01-ticket-chat-ai#194]
## User story
1. As a user that reports a problem
2. I don't want give my contact details every time I'm using the webapp
3. So that I don't have to waste time inputting this information again and again

## Task
In order to create a profile to later log in the webapp, users need to enter a name, passport and their office location: As name, the email adress should be used, which will be the same email to which all further communication will be send. The user is free to choose a password as he likes without any instructions for now. As location, only the defined office locations are valid. Once the user has logged in using his credentials, the system will recognise him automatically until he logs out. When the user is logged in, the text box to enter the e-mail above the text input field is not visible.

## Acceptance criteria
- [ ] users can create a profile
- [ ] the user name is a valid email adress
- [ ] only the defined office locations are accepted
- [ ] the user is able to log in with his profile
- [ ] if the user logged in once, he is automatically recognized until he actively logs out
- [ ] the user must be able to log out

## Definition of done (DoD)
- Work products are uploaded to the Github repository and merged to the main branch
- If necessary, the bill of materials section of the planning documents is updated
- Code/feature passes suited tests
- Code is peer-reviewed
- Help documentation (README) is updated
- Fits into our architecture, where possible

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release
